package com.dnf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setDaqv(java.lang.String daqv) {
		set("daqv", daqv);
		return (M)this;
	}

	public java.lang.String getDaqv() {
		return get("daqv");
	}

	public M setServer(java.lang.String server) {
		set("server", server);
		return (M)this;
	}

	public java.lang.String getServer() {
		return get("server");
	}

	public M setInventory(java.lang.Integer inventory) {
		set("inventory", inventory);
		return (M)this;
	}

	public java.lang.Integer getInventory() {
		return get("inventory");
	}

	public M setMoney(java.lang.Integer money) {
		set("money", money);
		return (M)this;
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public M setZhuan(java.lang.Integer zhuan) {
		set("zhuan", zhuan);
		return (M)this;
	}

	public java.lang.Integer getZhuan() {
		return get("zhuan");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

}
